# Generated by Django 4.2.7 on 2024-04-06 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='sentiment',
            field=models.FloatField(default=0.0),
        ),
    ]
