# Generated by Django 4.2.7 on 2024-04-08 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_post_options_post_caption_post_summary_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='summary',
        ),
    ]
